GET http://localhost:3006/api/comment


###

POST http://localhost:3006/api/comment
Content-Type: application/json

{
    "comment_id": 9,
    "content": "Test post comment",
    "last_updated": "11 minutes ago",
    "like_amount": 1,
    "parent_id": 0,
    "post_id": 1,
    "user_id": 2,
    "user_name": "NXD"
}